name: Deploy React App to GitHub Pages (Custom Domain)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages (no 3rd-party packages)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use token in the clone URL for authentication
          git clone --branch gh-pages https://${GITHUB_TOKEN}@github.com/${{ github.repository }} out || \
          git clone https://${GITHUB_TOKEN}@github.com/${{ github.repository }} out && \
          cd out && \
          git checkout --orphan gh-pages && \
          cd ..
          
          # Add debug step to check what files were generated
          echo "Contents of current directory:"
          ls -la
          
          # Copy build files (if they exist)
          if [ -d "dist" ]; then
            rm -rf out/*
            cp -r dist/* out/
          else
            echo "Error: dist directory not found. Check your build configuration."
            exit 1
          fi
          
          cd out
          touch .nojekyll
          git add .
          git commit -m "Deploy React App to GitHub Pages"
          git push --force https://${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}